const questions = [
    "1. Write a function to print the name of the class: 'class A'.",
    "2. Write a function to print the teacher's name: 'Mary'.",
    "3. Write a function to print the names of all the students in the class.",
    "4. Write a function to print the IDs of all the students in the class.",
    "5. Write a function to print the subject names for a specific student.",
    "6. Write a function to print the marks of a specific student in all subjects.",
    "7. Write a function to calculate and print the average marks for a specific student.",
    "8. Write a function to calculate and print the total marks for a specific student.",
    "9. Write a function to calculate and print the average marks for all students in a specific subject.",
    "10. Write a function to calculate and print the total marks for all students in a specific subject.",
    "11. Write a function to find and print the student with the highest marks in a specific subject.",
    "12. Write a function to find and print the student with the lowest marks in a specific subject.",
    "13. Write a function to find and print the student with the highest total marks.",
    "14. Write a function to find and print the student with the lowest total marks.",
    "15. Write a function to find and print the subject with the highest average marks.",
    "16. Write a function to find and print the subject with the lowest average marks.",
    "17. Write a function to calculate and print the overall average marks for the class.",
    "18. Write a function to calculate and print the overall total marks for the class.",
    "19. Write a function to calculate and print the average marks for each subject.",
    "20. Write a function to calculate and print the total marks for each subject.",
    "21. Write a function to find and print the subject with the highest total marks.",
    "22. Write a function to find and print the subject with the lowest total marks.",
    "23. Write a function to find and print the student(s) with the highest average marks.",
    "24. Write a function to find and print the student(s) with the lowest average marks.",
    "25. Write a function to find and print the student(s) with the highest total marks.",
    "26. Write a function to find and print the student(s) with the lowest total marks.",
    "27. Write a function to calculate and print the number of students who scored above a certain mark in a specific subject.",
    "28. Write a function to calculate and print the number of students who scored below a certain mark in a specific subject.",
    "29. Write a function to calculate and print the number of students who scored above a certain mark in all subjects.",
    "30. Write a function to calculate and print the number of students who scored below a certain mark in all subjects.",
    "31. Write a function to calculate and print the percentage of students who scored above a certain mark in a specific subject.",
    "32. Write a function to calculate and print the percentage of students who scored below a certain mark in a specific subject.",
    "33. Write a function to calculate and print the percentage of students who scored above a certain mark in all subjects.",
    "34. Write a function to calculate and print the percentage of students who scored below a certain mark in all subjects.",
    "35. Write a function to find and print the student(s) with the highest percentage of marks.",
    "36. Write a function to find and print the student(s) with the lowest percentage of marks.",
    "37. Write a function to find and print the subject(s) with the highest percentage of marks.",
    "38. Write a function to find and print the subject(s) with the lowest percentage of marks.",
    "39. Write a function to find and print the student(s) with the highest percentage of marks in a specific subject.",
    "40. Write a function to find and print the student(s) with the lowest percentage of marks in a specific subject.",
    "41. Write a function to find and print the subject(s) with the highest percentage of marks for a specific student.",
    "42. Write a function to find and print the subject(s) with the lowest percentage of marks for a specific student.",
    "43. Write a function to find and print the subject(s) in which all students scored above a certain mark.",
    "44. Write a function to find and print the subject(s) in which all students scored below a certain mark.",
    "45. Write a function to find and print the subject(s) in which the average marks of all students are above a certain mark.",
    "46. Write a function to find and print the subject(s) in which the average marks of all students are below a certain mark.",
    "47. Write a function to find and print the student(s) who scored the highest marks in at least one subject.",
    "48. Write a function to find and print the student(s) who scored the lowest marks in at least one subject.",
    "49. Write a function to calculate and print the average marks for each student in each subject.",
    "50. Write a function to calculate and print the total marks for each student in each subject.",
    "51. Write a function to find and print the student(s) who scored the highest marks in each subject.",
    "52. Write a function to find and print the student(s) who scored the lowest marks in each subject.",
    "53. Write a function to find and print the subject(s) in which the highest marks were scored.",
    "54. Write a function to find and print the subject(s) in which the lowest marks were scored.",
    "55. Write a function to find and print the student(s) who scored above the class average marks.",
    "56. Write a function to find and print the student(s) who scored below the class average marks.",
    "57. Write a function to find and print the subject(s) in which the average marks are above the class average marks.",
    "58. Write a function to find and print the subject(s) in which the average marks are below the class average marks.",
    "59. Write a function to find and print the subject(s) in which the highest percentage of students scored above a certain mark.",
    "60. Write a function to find and print the subject(s) in which the highest percentage of students scored below a certain mark.",
    "61. Write a function to find and print the subject(s) in which the lowest percentage of students scored above a certain mark.",
    "62. Write a function to find and print the subject(s) in which the lowest percentage of students scored below a certain mark.",
    "63. Write a function to calculate and print the percentage of students who scored above the class average marks in each subject.",
    "64. Write a function to calculate and print the percentage of students who scored below the class average marks in each subject.",
    "65. Write a function to calculate and print the percentage of students who scored above the class average marks in at least one subject.",
    "66. Write a function to calculate and print the percentage of students who scored below the class average marks in at least one subject.",
    "67. Write a function to find and print the student(s) who scored above the class average marks in all subjects.",
    "68. Write a function to find and print the student(s) who scored below the class average marks in all subjects.",
    "69. Write a function to find and print the student(s) who scored above the class average marks in the majority of subjects.",
    "70. Write a function to find and print the student(s) who scored below the class average marks in the majority of subjects.",
    "71. Write a function to find and print the subject(s) in which the majority of students scored above the class average marks.",
    "72. Write a function to find and print the subject(s) in which the majority of students scored below the class average marks.",
    "73. Write a function to calculate and print the percentage of students who scored above the average marks of a specific student in each subject.",
    "74. Write a function to calculate and print the percentage of students who scored below the average marks of a specific student in each subject.",
    "75. Write a function to calculate and print the percentage of students who scored above the average marks of a specific student in at least one subject.",
    "76. Write a function to calculate and print the percentage of students who scored below the average marks of a specific student in at least one subject.",
    "77. Write a function to find and print the student(s) who scored above the average marks of a specific student in all subjects.",
    "78. Write a function to find and print the student(s) who scored below the average marks of a specific student in all subjects.",
    "79. Write a function to find and print the subject(s) in which the average marks are above the average marks of a specific student.",
    "80. Write a function to find and print the subject(s) in which the average marks are below the average marks of a specific student.",
    "81. Write a function to find and print the subject(s) in which the highest percentage of students scored above the average marks of a specific student.",
    "82. Write a function to find and print the subject(s) in which the highest percentage of students scored below the average marks of a specific student.",
    "83. Write a function to find and print the subject(s) in which the lowest percentage of students scored above the average marks of a specific student.",
    "84. Write a function to find and print the subject(s) in which the lowest percentage of students scored below the average marks of a specific student.",
    "85. Write a function to calculate and print the percentage of students who scored above the average marks of the class in each subject.",
    "86. Write a function to calculate and print the percentage of students who scored below the average marks of the class in each subject.",
    "87. Write a function to calculate and print the percentage of students who scored above the average marks of the class in at least one subject.",
    "88. Write a function to calculate and print the percentage of students who scored below the average marks of the class in at least one subject.",
    "89. Write a function to find and print the student(s) who scored above the average marks of the class in all subjects.",
    "90. Write a function to find and print the student(s) who scored below the average marks of the class in all subjects.",
    "91. Write a function to find and print the student(s) who scored above the average marks of the class in the majority of subjects.",
    "92. Write a function to find and print the student(s) who scored below the average marks of the class in the majority of subjects.",
    "93. Write a function to find and print the subject(s) in which the majority of students scored above the average marks of the class.",
    "94. Write a function to find and print the subject(s) in which the majority of students scored below the average marks of the class.",
    "95. Write a function to calculate and print the percentage of students who scored above the average marks of a specific student in the majority of subjects.",
    "96. Write a function to calculate and print the percentage of students who scored below the average marks of a specific student in the majority of subjects.",
    "97. Write a function to calculate and print the percentage of students who scored above the average marks of a specific student in the majority of subjects.",
    "98. Write a function to calculate and print the percentage of students who scored below the average marks of a specific student in the majority of subjects.",
    "99. Write a function to find and print the subject(s) in which the highest percentage of students scored above the average marks of a specific student.",
    "100. Write a function to find and print the subject(s) in which the highest percentage of students scored below the average marks of a specific student.",
]


export default questions